vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       gallery:
            uri_prefix: '%uploads%'
            upload_destination: '%kernel.project_dir%/public%uploads%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: false